version: '3.6'

services:
    auth-app:
        build:
            context: .
            dockerfile: Dockerfile
        command: ['yarn', 'dev']
        ports:
            - 3001:3001
        volumes:
            - ./:/app/
        networks:
            - imdb
        depends_on:
            - auth-db

    auth-db:
        image: mysql
        command: ['--default-authentication-plugin=mysql_native_password']
        restart: always
        env_file: ./.mysql.env
        ports:
            - 3306:3306
        networks:
            - imdb

    auth-db-gui:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - imdb

networks:
    imdb:
        external: true
